"""Immutable action checks also protect consumers without generator manifests."""

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "workflow_contracts", Path(__file__).resolve().parents[1] / "scripts/workflow_contracts.py"
)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("Cannot load workflow contracts")
CONTRACTS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(CONTRACTS)


class ImmutableWorkflowTests(unittest.TestCase):
    """Exercise the public validator with no optional pin manifest present."""

    def validate(self, job):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / ".github/workflows").mkdir(parents=True)
            (root / ".release-policy.json").write_text("{}")
            (root / ".github/workflows/quality-gate.yml").write_text(
                "# Generated by venus-os-ci-toolkit/scripts/install_release.py;\n"
                + json.dumps({"jobs": {"check": job}})
            )
            CONTRACTS.validate(root, actions_only=True)

    def test_mutable_step_refs_are_rejected_without_manifest(self):
        for reference in ("actions/checkout@v7", "owner/action@main", "owner/action@abc1234"):
            with self.subTest(reference=reference), self.assertRaisesRegex(
                ValueError, "immutable SHA"
            ):
                self.validate({"steps": [{"uses": reference}]})

    def test_mutable_reusable_workflow_is_rejected_without_manifest(self):
        with self.assertRaisesRegex(ValueError, "immutable SHA"):
            self.validate({"uses": "owner/repo/.github/workflows/ci.yml@main"})

    def test_mutable_docker_refs_are_rejected(self):
        with self.assertRaisesRegex(ValueError, "immutable SHA"):
            self.validate({"steps": [{"uses": "docker://alpine:latest"}]})

    def test_pinned_and_local_refs_and_run_steps_are_valid(self):
        self.validate({"uses": "owner/repo/.github/workflows/ci.yml@" + "a" * 40})
        self.validate({"steps": [
            {"uses": "actions/checkout@" + "a" * 40},
            {"uses": "docker://alpine@sha256:" + "b" * 64},
            {"uses": "./.github/actions/local"},
            {"run": "true"},
        ]})


if __name__ == "__main__":
    unittest.main()
