name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: Terraform CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/terraform-ci.yml@90fae60a049bbd1a55ac218c379f36cb101299f1
    with:
      working-directory: '.'
